main/urls.py
from django.contrib import admin
from django.urls import path

from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.show_profile_or_list_of_notes, name='index'),
    path('add/', views.create_note_view, name='note_create'),
    path('edit/<int:pk>/', views.NoteUpdateView.as_view(), name='note_update'),
    path('delete/<int:pk>/', views.NoteDeleteView.as_view(), name='note_delete'),
    path('details/<int:pk>/', views.NoteDetailView.as_view(), name='note_detail'),

    # The smartest solution would be to add pk to the profile link.
    # But according to the conditions of the problem, it is necessary to do without pk.
    # Therefore, we redirect to the "correct" link )))
    path('profile/', views.redirect_to_profile, name='profile_redirect'),
    path('profiles/<int:pk>/', views.ProfileDeleteView.as_view(), name='profile_delete'),
]

notes/models.py
from django.db import models


class Profile(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    image_url = models.URLField()

    def __str__(self):
        return self.first_name + ' ' + self.last_name


class Note(models.Model):
    profile_id = models.ForeignKey(Profile, on_delete=models.CASCADE)
    title = models.CharField(max_length=30)
    image_url = models.URLField(blank=True)
    content = models.TextField()

    def __str__(self):
        return self.title

notes/forms.py
from django import forms

from notes.models import Profile, Note


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'


class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = '__all__'
        exclude = ['profile_id']

main/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import UpdateView, DeleteView, DetailView

from notes.forms import NoteForm, ProfileForm
from notes.models import Profile, Note


def show_profile_or_list_of_notes(request):
    is_profile_data = Profile.objects.exists()
    if is_profile_data:
        profile = Profile.objects.last()
        is_notes = Note.objects.exists()
        notes = []
        if is_notes:
            notes = Note.objects.all()
        context = {'is_notes': is_notes,
                   'notes': notes,
                   'profile': profile,
                   'notes_form': NoteForm()}
        return render(request, 'home-with-profile.html', context)
    else:
        if request.method == 'POST':
            profile = ProfileForm(request.POST)
            if profile.is_valid():
                profile.save()
            return redirect('index')
        else:
            context = {'form': ProfileForm()}
            return render(request, 'home-no-profile.html', context)


def create_note_view(request, **kwargs):
    if request.method == "POST":
        profile = Profile.objects.last()
        form = NoteForm(request.POST)
        if form.is_valid():
            note = form.save(commit=False)
            note.profile_id = profile
            print(type(profile))
            print(profile)
            note.save()
            return redirect('index')
        else:
            context = {'form': NoteForm(request.POST)}
            return render(request, 'note-create.html', context)

    context = {'form': NoteForm()}
    return render(request, 'note-create.html', context)


class NoteUpdateView(UpdateView):
    model = Note
    fields = ['title',  'image_url', 'content']
    template_name = 'note-edit.html'
    success_url = reverse_lazy('index')

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     # context['title'] = 'Edit page'
    #     note = context['note']
    #     # context['heading_text'] = f'Creating of {note.doc_name}'
    #     # context['description'] = f'On this page you can update the document {note.doc_name}.'
    #     return context


class NoteDeleteView(DeleteView):
    model = Note
    fields = ['title',  'image_url', 'content']
    template_name = 'note-delete.html'
    success_url = reverse_lazy('index')


class NoteDetailView(DetailView):
    model = Note
    fields = ['title',  'image_url', 'content']
    template_name = 'note-details.html'
    success_url = reverse_lazy('index')


def redirect_to_profile(request):
    pk = Profile.objects.last().pk
    return redirect(f'/profiles/{pk}')


class ProfileDeleteView(DeleteView):
    model = Profile
    template_name = 'profile.html'
    success_url = reverse_lazy('index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['notes_len'] = len(Note.objects.all())
        return context

templates/base-page.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" type="text/css" href="/static/css/style.css" />
        <title>Notes</title>
    </head>

    <body>
        <!--navigation bar-->
        <header>
            <nav>
                <ul>
                    <li class="img"><img src="/static/images/note.png" /></li>
                    <li><a href="/">Notes</a></li>
                    <li class="right">
                        <a href="{% url "note_create" %}">Add Note</a>
                        <a href="{% url "profile_redirect" %}">Profile</a>
                    </li>
                </ul>
            </nav>
        </header>
        <!--end navigation bar-->

{% block container %}




{% endblock container %}
        <!--end notes container-->

        <footer>
            <div>Python Web Basics Exam @SoftUni</div>
        </footer>
    </body>
</html>

templates/home-no-profile.html
{% extends 'base-page.html' %}
{% load static %}

{% block container %}
        <div class="body">
            <!--headings-->
            <h1>Enter Your Data</h1>
            <!--end headings-->

            <!--profile data form-->
            <div class="form">
                <form method="POST">
                    {% csrf_token %}
                    {{ form }}

                    <input type="submit" value="SUBMIT" />
                </form>
            </div>
            <!--end profile data form-->
        </div>

{% endblock container %}


templates/home-with-profile.html
{% extends 'base-page.html' %}
{% load static %}

{% block container %}

        <h1> My Notes </h1>

    {% if not is_notes %}
        <h2>There are no notes.</h2>
        <!--notes container-->
    {% else %}
        {% for note in notes %}
            <div class="note-container">
                <h2>{{ note.title }} <img src="{{ note.image_url}}" /></h2>

                <div class="right">
                    <a class="button details" href="{% url 'note_detail' note.pk %}">Details</a>
                    <a class="button edit" href="{% url 'note_update' note.pk %}">Edit</a>
                    <a class="button delete" href="{% url 'note_delete' note.pk %}">Delete</a>
                </div>
            </div>

        {% endfor %}

    {% endif %}

{% endblock container %}

templates/note-create.html
{% extends 'base-page.html' %}
{% load static %}

{% block container %}
        <div class="body">
            <!--headings-->
            <h1>Add Note</h1>
            <!--headings-->

            <!--note data form-->
            <div class="form">
                <form method="POST" action="{% url "note_create" %}">
                    {% csrf_token %}
                    {{ form}}

                    <input type="submit" value="Publish" />
                </form>
            </div>
            <!--end note data form-->
        </div>
{% endblock container %}

templates/note-delete.html
{% extends "base-page.html" %}
{% load static %}

{% block container %}

        <div class="body">
            <!--headings-->
            <h1>Delete Note</h1>
            <!--headings-->

            <!--note delete data form-->
            <div class="form">
                <form method="POST">
                    <input type="hidden" name="csrfmiddlewaretoken" value="hwapnt8nZjnQuJ2M6SZBuXGgOwc3fZlrekSnnyS6N1CJtVSbSytIlPT26Nac1auc" />
                    <label for="name">Note Title</label>
                    <input type="text" name="title" value="{{ note.title }}" maxlength="50" disabled="" required="" id="id_title" />

                    <label for="content">Content</label>
                    <textarea name="description" cols="40" rows="10" disabled="" required="" id="id_description">
                    {{ note.content }}
                    </textarea>

                    <label for="image_url">Link to Image</label>
                    <input type="url" name="image_url" value="{{ note.image_url }}" maxlength="200" disabled="" required="" id="id_image_url" />

                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" value="Delete" />
                </form>
            </div>
            <!--end note delete data form-->
        </div>

{% endblock container %}

templates/note-details.html
{% extends 'base-page.html' %}
{% load static %}

{% block container %}

        <div class="body">
            <!--headings-->
            <h1>Note Details</h1>
            <!--headings-->

            <!--details note box-->
            <div class="note-details-container">
                <h2>{{ note.title}}</h2>
                <img class="detail-img" src="https://www.freeiconspng.com/thumbs/tasks-icon/tasks-icon-9.png" alt="note-image" />
                <div>
                    <p>Content</p>
                </div>
                <p>{{ note.content }}</p>
                <div class="right">
                    <a class="button edit" href="{% url "note_update" note.pk %}">Edit</a>
                    <a class="button delete" href="{% url "note_delete" note.pk %}">Delete</a>
                </div>
            </div>
            <!--end details note box-->
        </div>


{% endblock container %}



templates/note-edit.html
{% extends 'base-page.html' %}
{% load static %}

{% block container %}

        <div class="body">
            <!--headings-->
            <h1>Edit Note</h1>
            <!--headings-->

            <!--note edit data form-->
            <div class="form">
                <form method="POST">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" value="Edit" />
                </form>
            </div>
            <!--end note edit data form-->
        </div>

{% endblock container %}



{#<html lang="en">#}
{#    <head>#}
{#        <meta charset="UTF-8" />#}
{#        <meta name="viewport" content="width=device-width, initial-scale=1.0" />#}
{#        <link rel="stylesheet" type="text/css" href="/static/css/style.css" />#}
{#        <title>Notes</title>#}
{#    </head>#}
{##}
{#    <body>#}
{#        <!--navigation bar-->#}
{#        <header>#}
{#            <nav>#}
{#                <ul>#}
{#                    <li class="img"><img src="/static/images/note.png" /></li>#}
{#                    <li><a href="/">Notes</a></li>#}
{#                    <li class="right">#}
{#                        <a href="/add">Add Note</a>#}
{#                        <a href="/profile">Profile</a>#}
{#                    </li>#}
{#                </ul>#}
{#            </nav>#}
{#        </header>#}
{#        <!--end navigation bar-->#}
{##}
{#        <div class="body">#}
{#            <!--headings-->#}
{#            <h1>Edit Note</h1>#}
{#            <!--headings-->#}
{##}
{#            <!--note edit data form-->#}
{#            <div class="form">#}
{#                <form method="POST">#}
{#                    {% csrf_token %}#}
{#                    {{ form }}#}
{#                    <input type="submit" value="Edit" />#}
{#                </form>#}
{#            </div>#}
{#            <!--end note edit data form-->#}
{#        </div>#}
{##}
{#        <!--footer-->#}
{#        <footer>#}
{#            <div>Python Web Basics Exam @SoftUni</div>#}
{#        </footer>#}
{#        <!--end footer-->#}
{#    </body>#}
{#</html>#}

templates/profile.html
{% extends 'base-page.html' %}
{% load static %}

{% block container %}

        <div class="body">
            <!--headings-->
            <h1>Your Profile</h1>
            <!--end headings-->

            <!--profile details container TODO-->
            <div class="note-container">
                <h2>
                    {{ profile }}
                    <img src="{{ profile.image_url }}" />
                </h2>
                <p>Age: {{ profile.age }}</p>
                <div>
                    <p>All notes: {{ notes_len }}</p>
                </div>
                <form method="POST">
                    <div class="right">
                        {% csrf_token %}
                        {{ form }}
{#                        <input type="submit" value="Delete" />#}
                        <button class="button delete"> Delete</button>
                    </div>
                </form>
            </div>
            <!--end profile details container-->
        </div>

{% endblock container %}
